stages:
  - setup
  - test
  - deploy

cache:
  paths:
    - node_modules/

install:
  stage: setup
  script: npm install

testing:
  stage: test
  script: npm test

deployment:
  stage: deploy
  environment:
    name: staging
    url: http://direct.sparling.us:11638
    on_stop: stop_deployment
  only:
    - master
  script: npm start

stop_deployment:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - npm stop
  when: manual
  environment:
    name: staging
    action: stop
