stages:
  - setup
  - test
  - deploy

cache:
  paths:
    - node_modules/

install:
  stage: setup
  script: npm install

testing:
  stage: test
  script: npm test

deployment_staging:
  stage: deploy
  environment:
    name: staging
    on_stop: stop_deployment_staging
  only:
    - master
  script: npm start

deployment_develop:
  stage: deploy
  variables:
    TE_PORT: '11637'
  environment:
    name: develop
    on_stop: stop_deployment_develop
  only:
    - develop
  script: npm start

stop_deployment_staging:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - npm stop
  when: manual
  environment:
    name: staging
    action: stop
  only:
    - master

stop_deployment_develop:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - npm stop
  when: manual
  environment:
    name: develop
    action: stop
  only:
    - develop
