FROM node:alpine AS build-env

WORKDIR /usr/src/app
COPY package*.json /usr/src/app/
COPY index.js /usr/src/app/
COPY src /usr/src/app/
RUN apk add git
RUN apk add python2
RUN apk add make
RUN apk add g++

CMD npm ci --production --quiet

FROM node:alpine

WORKDIR /usr/src/app
COPY --from=build-env /usr/src/app /usr/src/app

ENTRYPOINT ["node"]
CMD ["index.js"]
