openapi: 3.0.1
info:
  title: Tuffy Estates
  version: 0.1.0
  description: The is the backend specification.
servers:
  - url: 'http://localhost:11638/api'
    description: Local Development Server
  - url: 'https://tuffyestates.sparling.us:11638/api'
    description: Staging Server
  - url: 'https://tuffyestates.sparling.us:11637/api'
    description: Development Server
tags:
  - name: meta
    description: Pertaining to API inner workings
  - name: users
    description: Everything about users
paths:
  /:
    get:
      tags:
        - meta
      summary: Request API specification file
      operationId: retrieveApiSpec
      responses:
        '200':
          description: Success
          content:
            application/yaml:
              schema:
                type: string
  /users:
    post:
      tags:
        - users
      summary: Registers a user
      operationId: registerUser
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  description: Username for the user
                password:
                  type: string
                  description: Password for the user
      responses:
        '201':
          description: User registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessionSecret:
                    type: string
                    description: The session secret used to authenticate future requests
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    description: Human readable error message
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    description: Human readable error message
                    type: string
  /users/login:
    post:
      tags:
        - users
      summary: Authenticate a user
      operationId: loginUser
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  description: Username used to authenticate the user
                  minLength: 3
                password:
                  type: string
                  description: Password used to authenticate the user
                  minLength: 3
      responses:
        '200':
          description: Session token authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessionSecret:
                    type: string
                    description: The session secret used to authenticate future requests
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    description: Human readable error message
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    description: Human readable error message
                    type: string
  /users/logout:
    head:
      tags:
        - users
      summary: Deauthenticate a user
      description: This is a no op request. Nothing is actually done on the server. Deauthentication is handled by the client removing its session token from it's request Authentication header.
      operationId: logoutUser
      responses:
        '200':
          description: Session token revoked
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    description: Human readable error message
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    description: Human readable error message
                    type: string
      security:
        - BearerAuth: []

# Properties

  /properties:
    post:
      tags:                    [properties]
      summary:                 create property
      operationId:             createProperty
      requestBody:
        required:              true
        content:
          multipart/form-data:
            schema:
              $ref:            '#/components/Listing/properties'
      responses:
        201:
          description:         Create property
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessionSecret:
                    type: string
                    description: The session secret used to authenticate future requests
        400:
          description:         Bad request
          content:
            application/json:
              schema:
                $ref:          '#/components/Listing/Error'
  /properties/patch:
    post:
      tags:                    [properties]
      summary:                 update property
      operationId:             propertyUpdate
      requestBody:
        required:              true
        content:
          multipart/form-data:
            schema:
              type:            object
              required:        [username, password]
              properties:
                username:
                  type:        string
                  description: Username used to authenticate the user
                password:
                  type:        string
                  description: Password used to authenticate the user
      responses:
        200:
          description:         Session token authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessionSecret:
                    type: string
                    description: The session secret used to authenticate future requests
        400:
          description:         Bad request
          content:
            application/json:
              schema:
                $ref:          '#/components/Listing/Error'
  /properties/:id:
    get:
      tags:                    [properties]
      summary:                 show property with returned _id
      operationId:             logoutUser
      responses:
        200:
          description:         Session token revoked
        400:
          description:         Bad request
          content:
            application/json:
              schema:
                $ref:          '#/components/schemas/Error'
      security:
        - BearerAuth:          []



  # Message
  /message:
    post:
      tags:                    [message]
      summary:                 create message or chat box ?
      operationId:             createProperty
      requestBody:
        required:              true
        content:
          multipart/form-data:
            schema:
        #      $ref:            '#/components/Listing/properties'
      responses:
        201:
          description:         Create property
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessionSecret:
                    type: string
                    description: The session secret used to authenticate future requests
        400:
          description:         Bad request
          content:
            application/json:
              schema:
                $ref:          '#/components/Listing/Error'


components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          x-mongoose-index: true
          x-mongoose-unique: true
          description: Username for the user
        password:
          type: string
          description: Password for the user
    Message:
      type: object
      required:
        - text
        - author
        - recipient
      properties:
        text:
          type: string
          description: Message contents
        author:
          type: string
          x-mongoose-type: ObjectId
          description: Id of user that authored the message
        recipient:
          type: string
          x-mongoose-type: ObjectId
          description: Id of user that received the message
    Property:
      type: object
      required:
        - address
        - details
      properties:
        address:
          type: string
          description: Property's physical address
        details:
          type: object
          description: More details about a property
          required:
            - price
            - size
          properties:
            price:
              type: number
              description: Price of the property in USD
            size:
              type: number
              description: Size of the property in squarefeet
            features:
              type: array
              description: Features of the property
              items:
                type: string
                enum:
                  - office
                  - garage
                  - fireplace
                  - pool
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                description: Human readable error message
                type: string
    InternalError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                description: Human readable error message
                type: string
